#!/bin/bash

BTREE="~/Rpi-Stuff/builds"
KTREE="~/Rpi-Stuff/linux"
XTOOLS="~/Rpi-Stuff/tools/arm-bcm2708/x86-linux64-cross-arm-linux-hardfp/bin/bcm2708hardfp-"
TMPDIR="/tmp/rpi"

rm -fR $TMPDIR
mkdir -p $TMPDIR
cd $KTREE
make ARCH=arm menuconfig O=$BTREE

## Make Image first...
 make O=$BTREE ARCH=arm CROSS_COMPILE=$XTOOLS Image
## Modules as a seperate target...
 make O=$BTREE ARCH=arm CROSS_COMPILE=$XTOOLS modules
## Install all modules..
 make O=$BTREE ARCH=arm INSTALL_MOD_PATH=$TMPDIR CROSS_COMPILE=$XTOOLS modules_install

cp $BTREE/arch/arm/boot/Image $TMPDIR/kernel.img

exit 0
